### ISSUE TITLE
Toggle comments doesn't work

### ISSUE THREAD

**Issue by jullimullins** [plafue/language-plantuml#11]
Using ctrl-/ command adds wrong comment characters. See example below
/_state "fuel prices" as fp_/
should be
/'state "fuel prices" as fp'/

**Comment by majacal** [comment]
u can fix it in config.cson

```
".plantuml":
  editor:
    commentEnd: "'/ "
    commentStart: " /''"
```
